import { AElementComponent, toKebapCase } from "@vanilla-ts/core";
import { Checkbox, Div, Input, Select, Span, Text, TextArea, TextInput } from "@vanilla-ts/dom";
import { IElementComponent, INodeComponent } from "../../vanilla-ts-core/types/Interfaces.js";
import { Dialog, DialogCloseEvent, DialogOptions, DLG_CANCELLED } from "./Dialog.js";
import { StdDlgI18N_EN } from "./I18N/StdDialogI18N_EN.js";
import { IconButton } from "./IconButton.js";
import { LabeledCheckbox } from "./LabeledCheckbox.js";
import { LabeledInputComponent } from "./LabeledInputComponent.js";
import { LabeledRadioButtonGroup } from "./LabeledRadioButtonGroup.js";
import { RadioButtonGroup } from "./RadioButtonGroup.js";
import { btn_CANCEL, btn_NO, btn_OK, btn_YES, SEP, STD_DLG_CANCELLED, UNKNOWN_BTN } from "./StdDialogBtns.js";

/**
 * Type of a component to be used for the title (bar) of the dialog box. No further assumptions are
 * made regarding the design, functionality and content of this component. If used, it should comply
 * with the conventions for dialog boxes of the respective operating system on which the application
 * is running. This component always receives the class name `dlg-title`.\
 * If `StdDlgTitle` is a function, it will be called with the `StdDialog` instance into which the
 * title (bar) is to be mounted, so it is possible to use the dialog instance for advanced
 * customization like adding a button to the title (bar) which closes the dialog. This can be done,
 * for example, by installing a `once` event handler for the `dlg-show` event on `StdDialog.Dialog`
 * since it is guaranteed that the dialog will have its final form when this event is triggered.\
 * The function must return the title bar as an instance of `IElementComponent<HTMLElement>` (which
 * will also receive the class name `dlg-title`).
 */
export type StdDlgTitle = IElementComponent<HTMLElement> | ((dlg: StdDialog) => IElementComponent<HTMLElement>);

/**
 * Type of the inner content for standard dialogs.\
 * If `StdDlgContent` is a function, it will be called with the `StdDialog` instance into which the
 * content is to be mounted, so it is possible to use the dialog instance for advanced customization
 * of the content (parts). This can be done, for example, by installing a `once` event handler for
 * the `dlg-show` event on `StdDialog.Dialog` since it is guaranteed that the dialog will have its
 * final form when this event is triggered.\
 * The function must return an array where each element must be either a
 * string, an instance of a `Text` component or an instance of `INodeComponent<HTMLElement>`.
 */
export type StdDlgContent = string | Text | INodeComponent<HTMLElement> | (string | INodeComponent<HTMLElement> | Text)[] | ((dlg: StdDialog) => (string | Text | INodeComponent<HTMLElement>)[]);

/**
 * Type of the map used to translate the captions for buttons generated by instances of `StdDialog`.
 */
export type StdDlgI18N = { [key: symbol]: string; };

/** Options for creating instances of standard dialogs. */
export type StdDlgOptions = {
    /**
     * An optional component for the title (bar) of the dialog box. No further assumptions are made
     * regarding the design, functionality and content of this component. If used, it should comply
     * with the conventions for dialog boxes of the respective operating system on which the
     * application is running. This component always receives the class name `dlg-title`.
     */
    Title?: StdDlgTitle;
    /**
     * Component(s)/text(s) for the inner content of the dialog, either as a single value or as an
     * array of values.
     */
    Content: StdDlgContent;
    /**
     * A symbol or an array of symbols. Every symbol will be used to create a corresponding button
     * (instance of `IconButton`). At the same time the symbols are used for the return values of
     * the dialog.
     */
    Buttons: symbol | symbol[];
    /**
     * The component to be focused when the dialog is shown (the first time). `Focus` can take the
     * following values:
     * - `undefined` (or absent): The first button of {@link StdDlgOptions.Buttons} (or
     *   {@link StdDlgOptions.Buttons} itself) is focused.
     * - A symbol contained in or equal to {@link StdDlgOptions.Buttons}: This focuses the
     *   corresponding button.
     * - `null`: Nothing is focused.
     * - An instance of `IElementComponent<HTMLElement>`: This component is focused. The instance
     *   should be focusable and it must be contained in or equal to {@link StdDlgOptions.Content}.
     */
    Focus?: symbol | IElementComponent<HTMLElement> | undefined | null;
    /**
     * A callback that is executed, if one of the dialog buttons is clicked/pressed.
     * @param btn The button which was clicked/pressed to close the dialog. If the dialog is closed
     * by pressing the `Escape` key (provided `DlgOptions.CloseWithEscape` is `true`), `btn` is the
     * symbol {@link STD_DLG_CANCELLED}.
     * @param dlg The instance of `StdDialog` which is to be closed.
     * @returns `true`, if the dialog can be closed, `false` if the dialog should remain open.
     */
    OnClose?: (btn: symbol, dlg: StdDialog) => Promise<boolean>;
    /**
     * If `true`, the class name `vertical` is added to the dialog. This facilitates the creation of
     * CSS that is intended to layout the buttons vertically for common prompts, like on recent
     * editions of macOS.\
     * Default: `false` (which results in `horizontal` being added as a class name to the dialog).
     */
    Vertical?: boolean;
    /** A class name or an array of class names to be set on the dialog. */
    ClassNames?: string | null | undefined | (string | null | undefined)[];
    /**
     * A map with button caption translations _used only for the current standard dialog instance_.
     * A real world usage scenario would rather use a complete map that is statically set once on
     * application start with `StdDialog.I18N = {...}`. Default: The current value of
     * `StdDialog.I18N` (which initially is set to {@link StdDlgI18N_EN}).
     */
    I18N?: StdDlgI18N;
    /**
     * Options for the `Dialog` instance that is created by `new StdDialog()`.
     * @see {@link DialogOptions}
     */
    DlgOptions?: DialogOptions;
};

/**
 * Used as the caption for every button that is not contained in the current translation map for
 * button symbols (`StdDialogs.I18N` or instance of `StdDlgI18N` passed to the constructor).
 */
const I18N_UNKNOWN_BTN = "I18N_UNKNOWN_BTN";

/**
 * This class aims to ease the creation of common standard dialogs.
 * Standard dialogs often have the same structure: they have an title bar (optional), a content
 * area, and a bar with buttons.\
 * In the content area, the user is shown a simple message, offered a selection, or presented with
 * an area containing several components. The user can close the dialog using one of the buttons,
 * whereby the button used is also the return value of the dialog. If a dialog to be created meets
 * these requirements, `StdDialog` helps with its creation.\
 * Although `StdDialog` can be used for each individual dialog if necessary, it is designed more for
 * creating such dialogs with simple functions that generate a suitable dialog with just a few
 * parameters, display it (usually modally), and return a return value. Predefined examples are the
 * ready-made functions {@link msgDlg()}, {@link confirm()} and {@link queryInput()} in this module.
 * They also serve as examples of how to use `StdDialog`.\
 * __Notes:__
 * - `StdDialog` doesn't take regular buttons made out of components, instead JavaScript symbols are
 *   used to define them in a more abstract way. Internally `StdDialog` itself then creates buttons
 *   (`IconButton`) from the symbol definitions.
 * - Clicking/pressing any of the provided buttons always tries to close the dialog.
 */
export class StdDialog {
    protected static i18n_ = StdDlgI18N_EN;
    protected redispatchedDlgClose = Symbol();
    protected options: StdDlgOptions;
    protected dlg: Dialog;
    protected buttons = new Map<symbol, IconButton>();
    protected disposed = false;

    /**
     * Create a new standard dialog.
     * @param options Options for the new standard dialog.
     */
    constructor(options: StdDlgOptions,) {
        this.options = {
            /* eslint-disable jsdoc/require-jsdoc */
            Title: options.Title,
            Content: Array.isArray(options.Content) ? options.Content.slice(0) : options.Content,
            Buttons: Array.isArray(options.Buttons) ? options.Buttons.slice(0) : options.Buttons,
            Focus: options.Focus,
            OnClose: options.OnClose,
            Vertical: options.Vertical ?? false,
            ClassNames: Array.isArray(options.ClassNames) ? options.ClassNames.slice() : [options.ClassNames],
            I18N: options.I18N ? { ...options.I18N } : StdDialog.i18n_,
            DlgOptions: options.DlgOptions ? { ...options.DlgOptions } : {}
            /* eslint-enable */
        };
        this.buildDlg();
    }

    /**
     * Get/set the current static map of button captions to be used by default. If a different
     * translation map is required temporarily for a new standard dialog, this can be passed via
     * `options` in the constructor when the dialog is created (the static standard map is not
     * affected by this).
     */
    public static get I18N(): StdDlgI18N {
        return this.i18n_;
    }
    /** @inheritdoc */
    public static set I18N(v: StdDlgI18N) {
        this.i18n(v);
    }

    /**
     * Set the current static map of button captions to be used by default. If a different
     * translation map is required temporarily for a new standard dialog, this can be passed via
     * `options` in the constructor when the dialog is created (the static standard map is not
     * affected by this).
     * @param i18n The new map of button captions to be used by default.
     * @returns This class.
     */
    public static i18n(i18n: StdDlgI18N): typeof StdDialog {
        this.i18n_ = i18n;
        return this;
    }

    /**
     * Get a _copy_ of the current options of this standard dialog. Modifying this object has no
     * effect.
     */
    public get Options(): StdDlgOptions {
        this.checkDisposed();
        return structuredClone(this.options);
    }

    /**
     * Get the `Dialog` component instance created by this standard dialog instance. Intended to be
     * used only if access to the dialog content is needed (`<someStdDialog.ElementChildren>`,
     * `<someStdDialog.Children>`), for example to read out the values of contained checkboxes or
     * similar. The last element of `ElementChildren`/`Children` is always a `Div` component that
     * contains the generated icon buttons.
     */
    public get Dialog(): Dialog {
        this.checkDisposed();
        return this.dlg;
    }

    /**
     * Get the current return value of the dialog. This is the symbol that corresponds to the button
     * that has been clicked/pressed or the symbol {@link STD_DLG_CANCELLED}, if the dialog has been
     * cancelled by other means, e.g. by pressing the `Escape` key, if the underlying `Dialog`
     * instance was created with that option (`StdDlgOptions.DlgOptions.CloseWithEscape: true`).
     */
    public get ReturnValue(): symbol {
        this.checkDisposed();
        return this.dlg.ReturnValue === "__DLG_CANCELLED__"
            ? STD_DLG_CANCELLED
            : Array.isArray(this.options.Buttons)
                ? this.options.Buttons.find((e) => e.description === this.dlg.ReturnValue) || UNKNOWN_BTN
                : this.options.Buttons.description === this.dlg.ReturnValue
                    ? this.options.Buttons
                    : UNKNOWN_BTN;
    }

    /**
     * Get all buttons created by this standard dialog (as a copy, modifying this map has no effect
     * on the underlying internal map). Can be used to further manipulate individual buttons.
     */
    public get Buttons(): Map<symbol, IconButton> {
        this.checkDisposed();
        return new Map(this.buttons);
    }

    /**
     * Displays the dialog (non-modal).
     */
    public show(): void {
        this.checkDisposed();
        this.dlg.show();
    }

    /**
     * Displays the dialog (modal) and waits for the user to click/press one of the buttons provided
     * in the options passed to the constructor (which closes the dialog).
     * @returns The symbol corresponding to the button which was clicked/pressed. If the standard
     * dialog was created with the option `StdDlgOptions.DlgOptions.CloseWithEscape = true` it is
     * also possible to close the dialog by pressing `Escape`; in this case the returned value is
     * the symbol {@link STD_DLG_CANCELLED}.
     */
    public async showModal(): Promise<symbol> {
        this.checkDisposed();
        await this.dlg.showModal();
        return this.ReturnValue;
    }

    /**
     * Closes the dialog. Useful only if the dialog was shown non-modal.
     * @param returnValue An overridden/individual value for the `ReturnValue` of the dialog. This
     * does _not_ change the _current_ value of `ReturnValue` on the internal `Dialog` instance!
     */
    public close(returnValue?: string): void {
        this.checkDisposed();
        this.dlg.close(returnValue);
    }

    /**
     * Disposes of this dialog instance and all of its resources. The instance is then unusable and
     * any access to its properties and functions throws an error. `dispose()` should always be
     * called when the dialog instance is no longer needed.
     */
    public dispose(): void {
        this.checkDisposed();
        this.disposed = true;
        this.dlg.dispose();
        // @ts-ignore
        this.dlg = undefined;
        // @ts-ignore
        this.options = undefined;
        this.buttons.clear();
    }

    /**
     * Checks, if this dialog instance is already disposed of. In this case an exception is thrown.
     */
    protected checkDisposed() {
        if (this.disposed) {
            throw new Error("This instance of StdDialog is already disposed of.");
        }
    }

    /**
     * Builds the dialog according to the options given in the constructor.
     */
    protected buildDlg(): void {
        this.checkDisposed();
        this.buttons.clear();
        this.dlg = new Dialog(this.options.DlgOptions);
        const btnBar = new Div();
        this.dlg
            .addClass(
                Dialog.DefaultCSSClassName,
                "std-dialog",
                this.options.Vertical ? "vertical" : "horizontal",
                ...(this.options.ClassNames as Array<string>),
            )
            .append(
                typeof this.options.Title === "function" ? this.options.Title(this).addClass("dlg-title") : this.options.Title,
                ... (
                    typeof this.options.Content === "function"
                        ? this.options.Content(this)
                        : Array.isArray(this.options.Content)
                            ? this.options.Content
                            : [this.options.Content]
                ).map(e => typeof e === "string" ? new Text(e) : e),
                btnBar
                    .addClass("dlg-btn-bar")
                    .append(
                        ...(
                            Array.isArray(this.options.Buttons)
                                ? this.options.Buttons.map(e => e === SEP
                                    ? new Span().addClass("separator")
                                    : this.getButton(e, this.dlg))
                                : [this.getButton(this.options.Buttons, this.dlg)]
                        )
                    )
            )
            .once("dlg-shown", () => {
                toFocus
                    ? toFocus.focus()
                    : (<HTMLElement>document.activeElement)?.blur?.();
            })
            .on("dlg-close", async (ev: DialogCloseEvent) => {
                type RedispatchedEvent = DialogCloseEvent & { detail: Record<symbol, boolean>; }; // eslint-disable-line jsdoc/require-jsdoc
                if ((<RedispatchedEvent>ev).detail[this.redispatchedDlgClose]) {
                    return;
                }
                if (ev.$.ReturnValue === DLG_CANCELLED) {
                    ev.preventDefault();
                    ev.stopImmediatePropagation();
                    if (this.options?.OnClose && ![true, undefined, null].includes(await this.options.OnClose(STD_DLG_CANCELLED, this))) {
                        return;
                    }
                    const newEvent = new DialogCloseEvent(this.dlg, DLG_CANCELLED, true);
                    (<RedispatchedEvent>newEvent).detail[this.redispatchedDlgClose] = true;
                    if (this.dlg.dispatch(newEvent)) {
                        // `forceClose()` !!! Otherwise this would cause and endless `dlg-close`
                        // event loop!
                        this.dlg.forceClose(DLG_CANCELLED);
                    }
                }
            });
        let toFocus: IconButton | IElementComponent<HTMLElement> | undefined;
        if (this.options.Focus && this.options.Focus instanceof AElementComponent) {
            toFocus = this.options.Focus;
        } else if (this.options.Focus === undefined) {
            toFocus = this.buttons.values().next().value;
        } else if (this.options.Focus === null) {
            toFocus = undefined;
        } else if (Array.isArray(this.options.Buttons)) {
            toFocus = this.buttons.get(<symbol>this.options.Focus);
        } else {
            toFocus = this.buttons.values().next().value;
        }
    }

    /**
     * Creates a button for the dialog.
     * @param sym A symbol that denotes the button to be created.
     * @param dlg The `Dialog` instance containing the generated button.
     * @returns The button created.
     */
    protected getButton(sym: symbol, dlg: Dialog): IconButton {
        this.checkDisposed();
        const btn = new IconButton({ Caption: [this.options.I18N![sym] || I18N_UNKNOWN_BTN] }) // eslint-disable-line jsdoc/require-jsdoc
            .addClass(IconButton.DefaultCSSClassName, "std-dlg-btn")
            .on("click", async () => {
                if (!this.options?.OnClose || [true, undefined, null].includes(await this.options.OnClose(sym, this))) {
                    dlg.close(sym.description);
                }
            });
        this.buttons.set(sym, btn);
        return btn;
    }
}


/**
 * A collection of common standard dialog functions.
 * @todo Expand the list of functions.
 */

/**
 * Options for the `msgDlg()` function.
 */
export type MsgDlgOptions = {
    /** A component or function for the title (bar) of the dialog. */
    Title?: StdDlgTitle;
    /**
     * By default the `msgDlg()` function displays only the button `btn_OK`. This can be overridden
     * with the property `Buttons`.
     */
    Buttons?: symbol | symbol[];
    /**
     * The button to be focused when the dialog is shown (the first time). `Focus` can take the
     * following values:
     * - `undefined` (or omitted): The button `btn_OK` or the first button of `Buttons` is focused.
     * - A button (symbol) contained in or equal to `Buttons`: This focuses the corresponding
     *   button.
     * - `null`: Nothing is focused, so the user has to select a button manually.
     */
    Focus?: symbol;
    /**
     * A callback that is executed, if one of the dialog buttons is clicked/pressed.
     * @param btn The button which was clicked/pressed to close the dialog. If the dialog is closed
     * by pressing the `Escape` key, `btn` is the symbol {@link STD_DLG_CANCELLED}.
     * @param dlg The instance of `StdDialog` which is to be closed.
     * @returns `true`, if the dialog can be closed, `false` if the dialog should remain open.
     */
    OnClose?: (btn: symbol, dlg: StdDialog) => Promise<boolean>;
    /** If `true`, the buttons will be laid out vertically (see {@link StdDlgOptions.Vertical}). */
    Vertical?: boolean;
    /** A class name or an array of class names to be set on the dialog. */
    ClassNames?: string | null | undefined | (string | null | undefined)[];
    /**
     * A translation map for the buttons of the dialog. If this is omitted, the current static
     * translation map of `StdDialog` is used (see {@link StdDialog.I18N}).
     */
    I18N?: StdDlgI18N;
};

/**
 * Displays a modal dialog with arbitray content. The dialog shows only the button `btn_OK` by
 * default (see also {@link MsgDlgOptions.Buttons}). The dialog will be disposed of, when the
 * function returns.
 * @param content The content for the message dialog.
 * @param options Options for the message dialog.
 * @returns The button (symbol) which was clicked or the symbol {@link STD_DLG_CANCELLED}, if the
 * dialog was closed by pressing the `Escape` key.
 */
export async function msgDlg(content: StdDlgContent, options?: MsgDlgOptions): Promise<symbol> {
    const stdDlg = new StdDialog({
        /* eslint-disable jsdoc/require-jsdoc */
        Title: options?.Title,
        Content: content,
        Buttons: options?.Buttons ? [options?.Buttons].flat() : [btn_OK],
        Focus: options?.Focus === undefined
            ? [options?.Buttons].flat()[0] ?? btn_OK
            : options?.Focus === null
                ? null
                : options.Focus,
        OnClose: options?.OnClose,
        Vertical: options?.Vertical ?? false,
        ClassNames: ["msg-dlg", options?.ClassNames].flat(),
        I18N: options?.I18N
        /* eslint-enable */
    });
    const btn = await stdDlg.showModal();
    stdDlg.dispose();
    return btn;
}

/**
 * Options for the `confirm()` function.
 */
export type ConfirmOptions = {
    /** A component or function for the title (bar) of the dialog. */
    Title?: StdDlgTitle;
    /**
     * By default the `confirm()` function displays the buttons `btn_YES` and `btn_NO`. This can be
     * overridden with the property `Buttons`.
     */
    Buttons?: symbol | [symbol, symbol];
    /**
     * If the default buttons are overridden with `Buttons`, `confirm()` has no way to decide
     * whether the user has selected the equivalent of 'Yes' or 'No' (as with `btn_YES`), so
     * `ConfirmButton` should be used. `ConfirmButton` must be equal to or contained in `Buttons`.
     * If `ConfirmButton` is omitted, the first entry in `Buttons` (or `Buttons` itself) will be
     * used.
     */
    ConfirmButton?: symbol;
    /**
     * The button to be focused when the dialog is shown (the first time). `Focus` can take the
     * following values:
     * - `undefined` (or omitted): The button `btn_YES` or the first button of `Buttons` is focused.
     * - `btn_YES` or `btn_NO` or a button (symbol) contained in or equal to `Buttons`: This focuses
     *   the corresponding button.
     * - `null`: Nothing is focused, so the user has to select a button manually.
     */
    Focus?: symbol | undefined | null;
    /**
     * A callback that is executed, if one of the dialog buttons is clicked/pressed.
     * @param btn The button which was clicked/pressed to close the dialog. If the dialog is closed
     * by pressing the `Escape` key, `btn` is the symbol {@link STD_DLG_CANCELLED}.
     * @param dlg The instance of `StdDialog` which is to be closed.
     * @returns `true`, if the dialog can be closed, `false` if the dialog should remain open.
     */
    OnClose?: (btn: symbol, dlg: StdDialog) => Promise<boolean>;
    /** If `true`, the buttons will be laid out vertically (see {@link StdDlgOptions.Vertical}). */
    Vertical?: boolean;
    /** A class name or an array of class names to be set on the dialog. */
    ClassNames?: string | null | undefined | (string | null | undefined)[];
    /**
     * A translation map for the buttons of the dialog. If this is omitted, the current static
     * translation map of `StdDialog` is used (see {@link StdDialog.I18N}).
     */
    I18N?: StdDlgI18N;
};

/**
 * Displays a modal dialog in which the user is prompted to select either 'yes' or 'no' for the
 * displayed content. The dialog shows the buttons `btn_YES` and `btn_NO` by default (see also
 * {@link ConfirmOptions.Buttons} and {@link ConfirmOptions.ConfirmButton}). The dialog will be
 * disposed of, when the function returns.
 * @param content The content for the confirm dialog. If this is a string which is an empty string
 * or a string that only contains whitespace, a `Text` component with that string will be used
 * (which almost never has a visual representation).
 * @param options Options for the confirm dialog.
 * @returns `true` only if the button `btn_YES` was clicked/pressed, otherwise `false`.
 */
export async function confirm(content: StdDlgContent, options?: ConfirmOptions): Promise<boolean> {
    const confirmButton = options?.ConfirmButton ?? ([options?.Buttons].flat())[0] ?? btn_YES;
    const stdDlg = new StdDialog({
        /* eslint-disable jsdoc/require-jsdoc */
        Title: options?.Title,
        Content: content,
        Buttons: options?.Buttons ? [options.Buttons].flat() : [btn_YES, btn_NO],
        Focus: options?.Focus === undefined
            ? [options?.Buttons].flat()[0] ?? btn_YES
            : options?.Focus === null
                ? null
                : options.Focus,
        OnClose: options?.OnClose,
        Vertical: options?.Vertical ?? false,
        ClassNames: ["confirm", options?.ClassNames].flat(),
        I18N: options?.I18N
        /* eslint-enable */
    });
    const btn = await stdDlg.showModal();
    stdDlg.dispose();
    return btn === confirmButton;
}

/**
 * Options for the `queryInput()` function.
 */
export type QueryInputOptions = {
    /** A component or function for the title (bar) of the dialog. */
    Title?: StdDlgTitle;
    /**
     * An input component that is derived from the `Input`, `LabeledInputComponent`, `Select`,
     * `TextArea`, `RadioButtonGroup` or `LabeledRadioButtonGroup` component found in
     * `@vanilla-ts/dom`/`@vanilla-ts/components`. This gives a lot of flexibility for creating
     * input dialogs for various data types. If `Input` is omitted, an instance of `TextInput` from
     * `@vanilla-ts/dom` with no further configuration is used.
     */
    Input?: Input | LabeledInputComponent<Input> | Select | TextArea | RadioButtonGroup | LabeledRadioButtonGroup;
    /** The content to be displayed _after_ the input component. */
    AfterInput?: StdDlgContent;
    /**
     * By default the `queryInput()` function displays the buttons `btn_OK` and `btn_CANCEL`. This
     * can be overridden with the property `Buttons`.
     */
    Buttons?: symbol | symbol[];
    /**
     * If the default buttons are overridden with `Buttons`, `queryInput()` has no way to decide
     * whether the user has selected the equivalent of 'Yes' or 'No' (as with `btn_OK`), so
     * `ConfirmButton` should be used. `ConfirmButton` must be equal to or contained in `Buttons`.
     * If `ConfirmButton` is omitted, the first entry in `Buttons` (or `Buttons` itself) will be
     * used.
     */
    ConfirmButton?: symbol;
    /**
     * A callback that is executed, if one of the dialog buttons is clicked/pressed.
     * @param btn The button which was clicked/pressed to close the dialog. If the dialog is closed
     * by pressing the `Escape` key, `btn` is the symbol {@link STD_DLG_CANCELLED}.
     * @param dlg The instance of `StdDialog` which is to be closed.
     * @returns `true`, if the dialog can be closed, `false` if the dialog should remain open.
     */
    OnClose?: (btn: symbol, dlg: StdDialog) => Promise<boolean>;
    /**
     * If available, this function will be called, if the `ConfirmButton` is clicked/pressed. If the
     * function returns `true`, the dialog is closed, otherwise the dialog stays open.
     * @param value The `Value` property of the input component. This is always of type `string`,
     * except for inputs of type `Checkbox` or `LabeledCheckbox` where `value` is of type `boolean`.
     * @returns `true`, if the validation is successful, otherwise `false`.
     */
    Validate?: (value: string | boolean) => Promise<boolean>;
    /** If `true`, the buttons will be laid out vertically (see {@link StdDlgOptions.Vertical}). */
    Vertical?: boolean;
    /** A class name or an array of class names to be set on the dialog. */
    ClassNames?: string | null | undefined | (string | null | undefined)[];
    /**
     * A translation map for the buttons of the dialog. If this is omitted, the current static
     * translation map of `StdDialog` is used (see {@link StdDialog.I18N}).
     */
    I18N?: StdDlgI18N;
};

/**
 * Displays a modal dialog in which the user can enter a value in an input component. The dialog
 * shows the buttons `btn_OK` and `btn_CANCEL` by default (see also
 * {@link QueryInputOptions.Buttons} and {@link QueryInputOptions.ConfirmButton}). Pressing the
 * 'Enter' key while the input component has the focus is equivalent to clicking on the button
 * `btn_OK` (or the button denoted by `ConfirmButton`). The only exception is if `input` is an
 * instance of `TextArea`, in this case pressing `Enter` does not close the dialog, instead the
 * `Enter` key is handled by the `TextArea` component itself. The dialog will be disposed of, when
 * the function returns.
 * @param content The content for the query input dialog. This content is displayed _before_ the
 * input component. If this is a string which is an empty string or a string that only contains
 * whitespace, a `Text` component with that string will be used (which almost never has a visual
 * representation).
 * @param options Options for the query input dialog.
 * @returns An object with three properties:
 * - `OK`: `true` only if the button `btn_OK` (or the `ConfirmButton`) was clicked/pressed or the
 *   'Enter' key was pressed while the input component had the focus, otherwise `false`.
 * - `Value`: The value of the input component. If `Input` is an instance of `Checkbox` or
 *   `LabeledCheckbox` then `Value` reflects the `Checked` state of `Input` (`true` or `false`).
 * - `Button`: The button (symbol) which was clicked or the symbol {@link STD_DLG_CANCELLED}, if the
 *   dialog was closed by pressing the `Escape` key.
 */
export async function queryInput(content: StdDlgContent | null | undefined, options?: QueryInputOptions): Promise<{ OK: boolean; Value: string | boolean; Button: symbol, }> { // eslint-disable-line jsdoc/require-jsdoc
    const input = options?.Input
        ? options.Input
        : new TextInput;
    const stdDlg = new StdDialog({
        /* eslint-disable jsdoc/require-jsdoc */
        Title: options?.Title,
        Content: content ?? [],
        Buttons: options?.Buttons ? [options.Buttons].flat() : [btn_OK, btn_CANCEL],
        Focus: input,
        OnClose: options?.OnClose,
        Vertical: options?.Vertical ?? false,
        ClassNames: ["query-input", "query-" + toKebapCase(input.ClassName), options?.ClassNames].flat(),
        I18N: options?.I18N
        /* eslint-enable */
    });
    stdDlg.Dialog.insert(
        stdDlg.Dialog.Children.length - 1,
        input,
        ...[
            typeof options?.AfterInput === "function"
                ? options.AfterInput(stdDlg)
                : options?.AfterInput
        ]
            .flat()
            .filter(e => e !== undefined && e !== null)
            .map(e => typeof e === "string" ? new Text(e) : e)
    );
    const confirmButton = options?.ConfirmButton ?? ([options?.Buttons].flat())[0] ?? btn_OK;
    (input instanceof TextArea) || (<IElementComponent<HTMLElement>>input).on("keydown", async (ev: KeyboardEvent) => {
        if (ev.key === "Enter") {
            ev.preventDefault();
            ev.stopImmediatePropagation();
            if (!options?.Validate || await options.Validate((input instanceof Checkbox || input instanceof LabeledCheckbox) ? input.Checked : input.Value)) {
                stdDlg.Dialog.close(confirmButton.description);
            }
        }
    });
    stdDlg.Dialog.on("dlg-close", async (ev: DialogCloseEvent) => {
        // Only, if the confirm button was clicked/pressed! Otherwise the validation would be
        // executed for _every_ button and also the dialog couldn't be canceled!
        if (ev.$.ReturnValue === confirmButton.description) {
            ev.preventDefault();
            ev.stopImmediatePropagation();
            if (!options?.Validate || await options.Validate((input instanceof Checkbox || input instanceof LabeledCheckbox) ? input.Checked : input.Value)) {
                // `forceClose()` !!! Otherwise this would cause and endless `dlg-close` event loop!
                stdDlg.Dialog.forceClose(confirmButton.description);
            }
        }
    });
    const btn = await stdDlg.showModal();
    const result = {
        /* eslint-disable jsdoc/require-jsdoc */
        OK: btn === confirmButton,
        Value: (input instanceof Checkbox || input instanceof LabeledCheckbox) ? input.Checked : input.Value,
        Button: btn
        /* eslint-enable */
    };
    stdDlg.dispose();
    return result;
}
