import { Em, Hr, LiOl, LiUl, Ol, P, Ul } from "@vanilla-ts/dom";
import { BaseExample } from "../BaseExample.js";


const intro = `
Components that encapsulate the DOM element
%\`<li>\`|https://developer.mozilla.org/en-US/docs/Web/HTML/Element/li%
for ordered lists (§@dom/Ol§) and unordered lists (§@dom/Ul§). \`LiOl\` components also allow to set
an individual number with the first constructor argument. If this is set to \`undefined\`, the
number will be automatically generated by the browser.

**Classes:** \`@vanilla-ts/dom/LiOl\`, \`@vanilla-ts/dom/LiUl\`
`;

const example = `
### Code example

\`\`\`
import { Em, Hr, LiOl, LiUl, Ol, P, Ul } from "@vanilla-ts/dom";

new P("Shopping List:");
new Ul(
    // List items can be strings ...
    "Flour",
    "Baking powder",
    "Sugar",
    "Salt",
    "Oil",
    // ... or @vanilla-ts/dom/LiUl components ...
    new LiUl(
        "From the cooling shelf:",
        // ... or simply any other component, e.g. another @vanilla-ts/dom/Ul instance.
        new Ul(
            new LiUl("Eggs"),
            new LiUl("Milk")
        )
    )
);
new Hr();
new P("How to make a muffin:");
new Ol(
    // For \`Ol\` list items the same applies.
    new LiOl(0, "Relax (optional)."), // An individual number can be set for every list item
    "Mix flour, baking powder, sugar, and salt.",
    "In another bowl, mix eggs, milk, and oil.",
    "Stir both mixtures together.",
    "Fill muffin tray 3/4 full.",
    new Em("Bake for 20 minutes.")
);
\`\`\`
`;


export class LiOlUlEx extends BaseExample {
    constructor() {
        super("LiOl & LiUl");
    }

    /** @inheritdoc */
    protected override buildExample(): void {
        this.append(
            this.markdown(intro),
            this.example([
                new P("Shopping List:"),
                new Ul(
                    "Flour",
                    "Baking powder",
                    "Sugar",
                    "Salt",
                    "Oil",
                    new LiUl(
                        "From the cooling shelf:",
                        new Ul(
                            new LiUl("Eggs"),
                            new LiUl("Milk")
                        )
                    )
                ),
                new Hr(),
                new P("How to make a muffin:"),
                new Ol(
                    new LiOl(0, "Relax (optional)."),
                    "Mix flour, baking powder, sugar, and salt.",
                    "In another bowl, mix eggs, milk, and oil.",
                    "Stir both mixtures together.",
                    "Fill muffin tray 3/4 full.",
                    new Em("Bake for 20 minutes.")
                )
            ]),
            this.markdown(example),
        );
    }
}


new LiUl("Milk"),
    new LiUl(
        "Cheese",
        new Ul(
            new LiUl("Blue cheese"),
            new LiUl("Feta")
        )
    );
